[package]
name = "bevy-game-test"
version = "0.1.0"
authors = ["Wesley <oliveirawesleyrj@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.6.1"
rand = "*"
integer_scaling = "1.3.2"
